/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.mcpgateway.controller; import cn.zhuatech.mcpgateway.common.ApiResponse; import cn.zhuatech.mcpgateway.dto.McpGatewayDto.*; import cn.zhuatech.mcpgateway.service.McpGatewayService; import cn.zhuatech.mcpgateway.service.McpAccessPolicyService; import jakarta.validation.Valid; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/shopfloor") @PreAuthorize("hasAnyRole('DOMAIN_USER','ADMIN')") public class WorkspaceController {private final McpGatewayService service;private final McpAccessPolicyService policy;/**
                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                            */
public WorkspaceController(McpGatewayService service,McpAccessPolicyService policy){this.service=service;this.policy=policy;}/**
                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                         */
@GetMapping("/dashboard") public ApiResponse<Dashboard> dashboard(){return ApiResponse.ok(service.shopfloorDashboard());}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@PostMapping("/work-orders/{id}/reports") public ApiResponse<ReportResult> report(@PathVariable Long id,@Valid @RequestBody ReportRequest request){return ApiResponse.ok("网关处置反馈已提交",service.report(id,request));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
@PostMapping("/access-decision") public ApiResponse<McpAccessPolicyService.Result> decide(@Valid @RequestBody McpAccessPolicyService.Request request){return ApiResponse.ok("访问策略判定完成",policy.decide(request));}}
