/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
export const domain={
 code:'MCP',systemName:'知华 MCP 企业网关',englishName:'MODEL CONTEXT PROTOCOL GATEWAY',theme:{primary:'#147d77',dark:'#21333a',accent:'#d07a3f'},workspace:'AI 基础平台 / MCP 网关集群',fieldWorkspace:'Agent 平台组',period:'2026-08-02 · 实时',liveText:'调用流水于 10:41 更新',fieldContextLabel:'当前网关域',fieldContext:'生产区 · 华东',fieldUser:'陆遥',fieldRole:'MCP 接入工程师',adminUser:'何谨',adminRole:'AI 平台负责人',
 adminTitle:'企业 MCP 接入与策略中心',adminBreadcrumb:'MCP 网关 / 运行态势',adminSubtitle:'在一个入口注册 MCP 服务、执行最小权限策略、签发短期凭证并审计工具调用。',exportAction:'导出调用审计',createAction:'申请服务接入',chartTitle:'MCP 调用成功趋势',chartSubtitle:'成功率 / 服务等级目标',chartLabels:['08:00','09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00'],loadTitle:'服务调用负荷',loadSubtitle:'当前并发占网关域容量',recordsTitle:'近期 MCP 接入任务',recordsSubtitle:'按权限范围、外部写操作与上线窗口排序',issueTitle:'策略与运行风险',issueSubtitle:'需要平台负责人审批或协调的事项',
 recordName:'接入任务',itemName:'MCP 服务',unitName:'接入团队',batchName:'权限范围',planName:'工具数',doneName:'已验证',exceptionName:'拦截',unitLabel:'项',listBreadcrumb:'服务治理 / 接入中心',listSubtitle:'管理服务注册、工具清单、Schema 校验、权限审批、凭证和灰度发布。',listSummary:[['注册服务','42'],['在线工具','186'],['今日调用','28.6K'],['高风险审批','4',true]],tabs:['全部','待审核','联调中','灰度中','已上线'],
 fieldBreadcrumb:'MCP 网关 / 接入工程师工作台',fieldTitle:'MCP 服务接入工作台',fieldSubtitle:'当前 5 个接入任务 · 2 个外部写工具 · 工程师陆遥',fieldSecondary:'查看网关运行日志',reportAction:'提交联调结果',fieldNoticeTitle:'生产网关集群运行稳定',fieldNotice:'过去 30 分钟成功率 99.96%，P95 延迟 128ms',steps:['服务登记','Schema 校验','权限审批','沙箱联调','灰度上线'],documentAction:'查看接入规范',printAction:'导出工具清单',resourceCardTitle:'网关基础设施',resourceValueLabel:'注册工具',resourceHealthLabel:'调用成功率',quickSubtitle:'接入工程师常用入口',quickActions:[['联调记录','/shopfloor/report','Schema、策略与调用结果'],['服务目录','/shopfloor/material','服务、工具和版本检索'],['网关状态','/shopfloor/resources','集群、延迟和凭证服务'],['风险审批','/shopfloor/andon','外部写、敏感数据和高权限']],
 reportDefaults:[6,1],reportTitle:'MCP 接入联调反馈',reportSubtitle:'记录已通过工具、策略拦截和异常说明。',reportSuccess:'联调结果已进入接入流水',reportPlaceholder:'填写工具名称、请求摘要、策略结果和修复建议',reportFootnote:'敏感参数仅保存摘要，不在演示数据中留存',ruleTitle:'网关准入基线',ruleSubtitle:'MCP-GW-POLICY · V1.4',rules:[['服务注册','必须完成'],['凭证范围','服务与工具级'],['外部写操作','人工审批'],['审计保留','180 天',true]],fieldTotals:[['42','注册 MCP 服务'],['186','在线工具'],['99.96%','调用成功率'],['128ms','P95 延迟']],
 adminMenus:[['/admin','home','网关运行中心'],['/admin/work-orders','order','接入任务'],['/admin/samples','box','服务目录'],['/admin/schedule','calendar','发布计划'],['/admin/methods','process','访问策略'],['/admin/reviews','quality','权限审批'],['/admin/resources','machine','网关集群'],['/admin/report','chart','调用分析']],fieldMenus:[['/shopfloor','home','接入工作台'],['/shopfloor/report','report','联调反馈'],['/shopfloor/tasks','order','我的接入'],['/shopfloor/material','box','服务目录'],['/shopfloor/resources','machine','网关状态'],['/shopfloor/andon','risk','风险审批',4]],
 moduleTitles:{tasks:['我的接入任务','查看权限范围、联调进度与上线窗口'],material:['MCP 服务目录','检索服务端、工具、Schema、版本和负责人'],resources:['网关集群','查看实例健康、延迟、限流和凭证签发'],andon:['风险审批','提交外部写、敏感数据或高权限工具审批'],samples:['服务目录','统一注册 MCP Server、Tool、Prompt 和 Resource'],schedule:['发布计划','协调沙箱、灰度与生产发布时间'],methods:['访问策略','维护主体、工具、参数与数据范围规则'],reviews:['权限审批','执行最小权限和职责分离审批'],report:['调用分析','分析流量、延迟、错误率和策略命中']},tagline:'给企业 Agent 一个可控、可审计的工具入口',storyTitle:'工具越多，<br/>越需要清晰的访问边界。',storyText:'连接 Agent 与企业系统的 MCP 服务治理、策略执行和调用审计底座。',pattern:[1,2,5,8,11,14,17,20,23,26,29,32],loginStats:[['186','在线工具'],['99.96%','调用成功率'],['128ms','P95 延迟']],loginTitle:'企业 MCP 接入与策略中心',adminDemo:'服务 / 策略 / 审计',fieldDemo:'接入 / 联调 / 灰度'
}
export const records=[{no:'MCP-260801-018',name:'CRM 客户查询工具接入',code:'CRM-CONNECTOR',unit:'Agent 平台组',group:'AI 基础平台',plan:24,done:16,exception:1,due:'08-03',batch:'只读范围',status:'联调中',progress:67,priority:'正常'},{no:'MCP-260801-021',name:'企业知识库检索服务接入',code:'DOC-SEARCH',unit:'数据连接器组',group:'数据平台',plan:18,done:8,exception:2,due:'08-03',batch:'敏感数据',status:'策略复核',progress:48,priority:'关注'},{no:'MCP-260802-006',name:'邮件发送工具写权限审批',code:'MAIL-SENDER',unit:'办公自动化组',group:'企业应用中心',plan:12,done:0,exception:0,due:'08-05',batch:'外部写',status:'待审批',progress:12,priority:'加急'},{no:'MCP-260728-015',name:'日程只读工具季度复核',code:'CALENDAR-READ',unit:'办公自动化组',group:'企业应用中心',plan:20,done:20,exception:1,due:'08-01',batch:'只读范围',status:'已上线',progress:100,priority:'正常'},{no:'MCP-260802-011',name:'工单系统状态更新工具接入',code:'TICKET-WRITE',unit:'Agent 平台组',group:'AI 基础平台',plan:16,done:11,exception:3,due:'08-04',batch:'内部写',status:'沙箱验证',progress:72,priority:'关注'}]
export const resources=[{code:'GW-EDGE-01',name:'生产 MCP 网关集群',unit:'AI 基础平台',status:'在线',health:99,value:'186',valueUnit:'工具',note:'P95 延迟 128ms'},{code:'GW-SANDBOX-02',name:'工具沙箱执行池',unit:'AI 基础平台',status:'在线',health:94,value:'36',valueUnit:'实例',note:'当前并发利用率 68%'},{code:'GW-SECRET-04',name:'短期凭证签发服务',unit:'企业应用中心',status:'预警',health:78,value:'12m',valueUnit:'TTL',note:'1 个连接器仍使用长期凭证'}]
export const reviews=[{no:'APR-260801-032',title:'邮件发送工具外部写审批',type:'高风险权限',detail:'4 个参数范围 · 何谨',result:'待确认'},{no:'APR-260801-011',title:'CRM 查询字段最小化复核',type:'数据权限',detail:'18 个字段 · 陆遥',result:'通过'},{no:'APR-260728-018',title:'长期凭证迁移检查',type:'凭证治理',detail:'剩余 1 个连接器',result:'异常'}]
export const adminMetrics=[['注册 MCP 服务','42','本月新增 7 个','blue'],['今日工具调用','28.6K','成功率 99.96%','green'],['策略拦截','126','高风险调用 18 次','orange'],['待权限审批','4','2 项涉及外部写','red']]
export const fieldMetrics=[['我的接入','5','2 个外部写工具','blue'],['今日已验证','31','工具调用场景','green'],['策略拦截','7','3 项待修复','orange'],['网关成功率','99.96%','P95 128ms','slate']]
export const chartActual=[94,96,97,98,98,99,99,99,100],chartTarget=[95,96,97,98,99,99,99,100,100]
export const loads=[['企业应用连接器',82,'8.4K 次/小时'],['数据检索服务',74,'6.8K 次/小时'],['研发工具服务',61,'4.2K 次/小时'],['办公协同服务',48,'2.6K 次/小时']]
export const issues=[{type:'权限',title:'邮件发送工具申请外部收件人写权限',detail:'需限定域名与单次收件人数',status:'待审批'},{type:'凭证',title:'工单连接器仍使用长期访问令牌',detail:'计划迁移短期范围凭证',status:'整改中'},{type:'Schema',title:'知识检索工具返回字段发生变更',detail:'影响 3 个生产 Agent',status:'灰度中'}]
